version: '3.5'

volumes:
    scc_mysql_data:
      name: scc_mysql_data

services:

  mysql-scc-dev:
    image: mysql:5.7
    container_name: mysql-scc-dev
    volumes:
      - scc_mysql_data:/var/lib/mysql/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
#      - MYSQL_DATABASE=ignition
