version: '3.5'

volumes:
    scc_mysql_data:
      name: scc_mysql_data

networks:
  scc_network:
    name: scc_network
    
services:

  scc-nginx:
    image: scc-nginx:1.13.6.1-0
    container_name: scc-nginx-srv
    ports:
      - 80:80
      - 443:443
    environment:
      sccInstanceHostPort: ${SCC_APP_WEB_HOST_PORT}
    networks:
      - scc_network

  mysql-scc-dev:
    image: mysql:5.7
    container_name: mysql-scc-dev
    volumes:
      - scc_mysql_data:/var/lib/mysql/
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    networks:
      - scc_network
